blank_issues_enabled: false
contact_links:
  - name: 🆕 Feature Request
    url: https://github.com/AllTheMods/All-the-mods-9-Sky/discussions/categories/modpack-content
    about: "Create a discussion about your new feature/suggestion"
  - name: 🐞 Mod Bug
    url: https://github.com/AllTheMods/All-the-mods-9-Sky/blob/main/MOD_ISSUES.md
    about: "List of Mod's Issue pages"
  - name: "❓ I don't know, I just need help"
    url: https://discord.gg/allthemods
    about: "Join our Discord channel: #9sky-techsupport"
