
[client]
	#Show item tags in tooltips (useful for custom EMC registration)
	tagToolTips = false
	#Show the EMC value as a tooltip on items and blocks
	emcToolTips = true
	#Requires holding shift to display the EMC value as a tooltip on items and blocks. Note: this does nothing if emcToolTips is disabled.
	shiftEmcToolTips = false
	#Requires holding shift to display the learned/unlearned text as a tooltip on items and blocks. Note: this does nothing if emcToolTips is disabled.
	shiftLearnedToolTips = true
	#Show stats as tooltips for various ProjectE blocks
	statToolTips = true
	#Show DM pedestal functions in item tooltips
	pedestalToolTips = true
	#The Philosopher's Stone overlay softly pulsates
	pulsatingOverlay = false

