
#Note: The majority of config options are in the server config file. If you do not see the server config file, try opening up a single player world. ProjectE uses one "server" config file for all worlds, for convenience in going from one world to another, but makes it be a "server" config file so that forge will automatically sync it when we connect to a multiplayer server.
[common]
	#Enable more verbose debug logging
	debugLogging = false
	#The Tome of Knowledge can be crafted.
	craftableTome = false
	#Require full omega klein stars in the tome of knowledge and gem armor recipes. This is the same behavior that EE2 had.
	fullKleinStars = false

