
#.
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]
	#.
	#Choose the menu row that the Create config button appears on in the main menu
	#Set to 0 to disable the button altogether
	#Range: 0 ~ 4
	mainMenuConfigButtonRow = 0
	#.
	#Choose the menu row that the Create config button appears on in the in-game menu
	#Set to 0 to disable the button altogether
	#Range: 0 ~ 5
	ingameMenuConfigButtonRow = 0
	